vaadin:
  url-mapping: /*

spring:
  application:
    name: vaadin
  data:
    mongodb:
      uri: "mongodb://admin:pass@mongo:27017/contact"
      auto-index-creation: true
  profiles:
    active: "prod"

  servlet:
    multipart:
      enabled: false
